---
title: "Datasets"
format:
  html:
    theme: default
    toc: true
    number-sections: true
jupyter: python3
---

# Dataset 1

[AirPassengers.csv](AirPassengers.csv)

The AirPassenger dataset in R provides monthly totals of a US airline passengers, from 1949 to 1960

# Dataset 2

[tourism.csv](tourism.csv)

Australian domestic overnight trips

**Description**

A dataset containing the quarterly overnight trips from 1998 Q1 to 2016 Q4 across Australia.

The dataset contains 23,408 rows and 5 variables:

**Variable description**

> Quarter: Year quarter (index)

> Region: The tourism regions are formed through the aggregation of Statistical Local Areas (SLAs) which are defined by the various State and Territory tourism authorities according to their research and marketing needs

> State: States and territories of Australia

> Purpose: Stopover purpose of visit: "Holiday", "Visiting friends and relatives","Business", "Other reason"

> Trips: Overnight trips in thousands

Reference

Wang, E, D Cook, and RJ Hyndman (2020).
  A new tidy data structure to support
  exploration and modeling of temporal
  data, Journal of Computational and
  Graphical Statistics, 29:3, 466-478,
  doi:10.1080/10618600.2019.1695624.