project:
  type: website

website:
  title: "Spatio-Temporal Data Analysis"
  description: "The course website for DSA 554 3.0 Spatio-Temporal Data Analysis"
  navbar:
    right:
      - text: Course materials
        href: blog.qmd
      - icon: github
        href: https://github.com/thiyangt
      - icon: twitter
        href: https://twitter.com/home
format:
  html:
    theme: cosmo
    css: styles.css



