---
title: "Week 11: Kriging"
format:
  revealjs:
    slide-number: true
    show-slide-number: all 
jupyter: python3
---

```{python}
#| fig-column: margin
#| echo: false
import numpy
import matplotlib.pyplot as plt

```



## Random process

- The value of a property at any place $x$, is denoted by $z(x)$. The $z(x)$ is one of an infinity of values of a
random variable $Z(x)$ at that place. We call it a ‘realization’ of the
process.



- The set of random values at all such places, again infinite in number,
in a region is a random process, and also denoted $Z(x)$.



- The random variable is spatially correlated at some scale.

## Stationarity

The notion of stationarity underpins geostatistics and allows us to
assume that there is the same degree of variation from place to place.

We can represent the random process by the model

$$Z(x) = \mu + \epsilon(x)$$

where $\mu$ is the mean of the process and $\epsilon(x)$ is a random quantity with a
mean of zero and a covariance, $C(\textbf{h})$, given by

$$C(\textbf{h}) = E[\epsilon(x)\epsilon(x+\textbf{h})]$$

which is equivalent to

$$
\begin{aligned}
C(h) &= E[(Z(x)-\mu)(Z(x+h)-\mu)] \\
&= E[Z(x)Z(x+h)-\mu^2]
\end{aligned}
$$

In these equations $h$ is the separation between samples in both distance
and direction; $Z(x)$ and $Z(x + h)$ are the values of $Z$ at places $x$
and $x + h$.

##

Under a weaker assumption of intrinsic stationarity in which the
expected differences are zero, i.e. $E[Z(x) − Z(x + h)] = 0$.

Then,

$$
\begin{aligned}
\gamma(\textbf{h}) &= \frac{1}{2}var[z(x)-z(x+h)]\\ &= \frac{1}{2}E[\{Z(x) - Z(x+\textbf{h})\}^2]
\end{aligned}
$$

## Covariance function and correlogram

$$\gamma(\textbf{h}) = C(0) - C(\textbf{h})$$

Correlogram

$$\rho(\textbf{h})= \frac{C(\textbf{h})}{\sigma^2}$$

## Computing and modelling variograms

1. Plot the experimental variogram.

2. Choose several models that appear to have the right shape and fit
each in turn by weighted least squares (Cressie, 1985; McBratney
andWebster, 1986) in an accredited program.

3. Plot the fitted models on the graph of the experimental variogram
and assess whether the fit looks reasonable.

4. If all plausible models seem to fit well, choose the one with the
smallest residual sum of squares (RSS) or smallest mean square.



##

5. One might be able to improve a fit in the above sense by elaborating
themodel. Any combination of the simple valid models is itself valid. The Akaike information criterion,
the AIC (Akaike, 1973), may help to answer. The aim is to minimize it (Webster and McBratney,
1989; Webster and Oliver, 2007).

## Factors affect the reliability of the experimental variogram

- Size of sample

- Lag interval and bin width

- Marginal distribution of the data

- Anisotropy

- Trend

## cross-validation provides a means of choosing among plausiblemodels for variograms


- Each
and every one of the $N$ data points is omitted in turn fromthe set of data
and its value there is predicted by ordinary punctual kriging with the
proposed model. 

- Three statistics are then calculated; they are the
mean error (ME), themean squared error (MSE) and themean squared
deviation ratio (MSDR)



## Example: Data

- `meuse` dataset contains measurements for concentrations of different elements, over an area in the Netherlands.

##

```{python}
#| fig-column: margin
#| echo: true
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotnine
import skgstat as skg
from pprint import pprint
from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
import warnings
warnings.filterwarnings("ignore")
```


## Load data


```{python}
#| fig-column: margin
#| echo: true
src = skg.data.meuse()
print(src.get('origin'))

coords, vals = src.get('sample')
# make a nice table
df = pd.DataFrame({'x': coords[:, 0], 'y': coords[:, 1], 'lead': vals.flatten()})
df.head()
```

##

Plotting the x and y coordinates and visually inspect how the z spread out.

```{python}
#| fig-column: margin
#| echo: true
fig, ax = plt.subplots(1, 1, figsize=(9, 9))
art = ax.scatter(coords[:, 0], coords[:, 1], s=50, c=vals.flatten(), cmap='plasma')
plt.colorbar(art)


```

#

```{python}
#| fig-column: margin
#| echo: true

(ggplot(df, aes('x', 'y', color='lead'))
 + geom_point())

```


# Variogram modelling

- How to choose an appropriate model function

- How to judge fitting quality

- Sample size influence

Source: https://scikit-gstat.readthedocs.io/en/latest/auto_examples/tutorial_03_variogram_models.html#sphx-glr-auto-examples-tutorial-03-variogram-models-py


# Kriging

$$Z(x) = \mu + \epsilon(x)$$

**Ordinary kriging:** $\mu$ is an unkown constant

**Simple kriging:** $\mu$ is a known constant

**Universal kriging:** $\mu(s)$ is some deterministic function




# Variogram modelling

Kriging


https://scikit-gstat.readthedocs.io/en/latest/auto_examples/tutorial_01_getting_started.html

